PREFIX    :   <http://purl.org/eis/vocab/scor#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#> 

SELECT ?node (sum(?totalCost) as ?hasMetricCO_23)
WHERE{
?process :belongsToNode ?node .
?process :hasMetricCO_9 ?x .
?process :hasMetricCO_10 ?y .
?process :hasMetricCO_11 ?z .
?process :hasMetricCO_12 ?w .
?process :hasMetricCO_13 ?b .
?process :hasMetricCO_14 ?c .
?process :hasMetricCO_15 ?d .
?process :hasMetricCO_16 ?e .
?process :hasMetricCO_17 ?a .
BIND(xsd:integer(?x) + xsd:integer(?y) + xsd:integer(?z) + xsd:integer(?w) + xsd:integer(?a)+ xsd:integer(?b)+ xsd:integer(?c)+ xsd:integer(?d)+ xsd:integer(?e) as ?totalCost)
}
GROUP BY (?node)
