PREFIX    :   <http://purl.org/eis/vocab/scor#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#> 

SELECT ?node (sum(?totalCost) as ?hasMetricCO_25)
WHERE{
?process :belongsToNode ?node .
?process :hasMetricCO_28 ?x .
?process :hasMetricCO_29 ?y .
?process :hasMetricCO_30 ?z .
BIND( xsd:integer(?x) + xsd:integer(?y) + xsd:integer(?z) as ?totalCost)
}
GROUP BY (?node)
