PREFIX    :   <http://purl.org/eis/vocab/scor#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#> 

SELECT ?node (sum(?totalCost) as ?hasMetricCO_22)
WHERE{
?process :belongsToNode ?node .
?process :hasMetricCO_5 ?x .
?process :hasMetricCO_8 ?y .
?process :hasMetricCO_6 ?z .
?process :hasMetricCO_7 ?w .
BIND( xsd:integer(?x) + xsd:integer(?y) + xsd:integer(?z) + xsd:integer(?w) as ?totalCost)
}
GROUP BY (?node)
