PREFIX    :   <http://purl.org/eis/vocab/scor#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#> 

SELECT ?node (sum(?totalCost) as ?hasMetricCO_24)
WHERE{
?process :belongsToNode ?node .
?process :hasMetricCO_19 ?x .
?process :hasMetricCO_20 ?y .
?process :hasMetricCO_18 ?z .
?process :hasMetricCO_321 ?w .
?process :hasMetricCO_322 ?b .
?process :hasMetricCO_323 ?c .
?process :hasMetricCO_324 ?d .
?process :hasMetricCO_325 ?e .
?process :hasMetricCO_27 ?a .
?process :hasMetricCO_26 ?g .
BIND(xsd:integer(?x) + xsd:integer(?y) + xsd:integer(?z) + xsd:integer(?w) + xsd:integer(?a)+ xsd:integer(?b)+ xsd:integer(?c)+ xsd:integer(?d) + xsd:integer(?e) + xsd:integer(?g) as ?totalCost)
}
GROUP BY (?node)
