PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://purl.org/eis/vocab/scor#>
Prefix ns: <http://www.semanticweb.org/ramzy/ontologies/2021/3/untitled-ontology-6#>
Select ?node ?tier ?min
where{
?node ns:belongsToTier ?tier.
?node :hasCostMetric ?min. 

{
Select ?tier (MIN(?metric) as ?min) {
?node :hasCostMetric ?metric. 
?node ns:belongsToTier ?tier.
} 
Group by (?tier)
}
}
