PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://purl.org/eis/vocab/scor#>
PREFIX    :   <http://purl.org/eis/vocab/scor#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#> 

SELECT (xsd:double((?value1
				   +?value2
				   +?value3
				   )/3) AS ?metricResult)
WHERE 
{
	?order :hasMetricAG_6  ?value1 .
	?order :hasMetricAG_7  ?value2 .
	?order :hasMetricAG_8  ?value3 .
	
}

