PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://purl.org/eis/vocab/scor#>

SELECT DISTINCT ?node (((?perfectorder / ?notFull) * 100) as ?hasMetricRL_21)
WHERE {
{SELECT ?node (count(?node) as ?perfectorder)  
WHERE{
?deliveredInFull :belongsToNode ?node .
?node  :hasMetricRL_24 ?perfectcondition.
?node :hasMetricRL_23 ?documentation.
?node :hasMetricRL_22 ?deliveryperformance.
?node :hasMetricRL_21 ?ordersdeliveredinfull.
 FILTER (perfectcondition > 90 && ?documentation> 90 && ?deliveryperformance> 90 && ?ordersdeliveredinfull> 90)

}
GROUP BY (?node)
} 
{SELECT ?node (count(?orders) as ?full)  
WHERE{
?order :belongsToNode ?node .
?node  :hasMetricRL_24 ?perfectcondition.
?node :hasMetricRL_23 ?documentation.
?node :hasMetricRL_22 ?deliveryperformance.
?node :hasMetricRL_21 ?ordersdeliveredinfull. 
}
GROUP BY (?node)
}
}