PREFIX : <http://purl.org/eis/vocab/scor#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
Prefix ns: <http://www.semanticweb.org/ramzy/ontologies/2021/3/untitled-ontology-6#>

Select ?node ?loc ?downnode ?loc2 abs(?diff){
?node ns:hasLocation ?loc. 
?node ns:belongsToTier ?tier.
?node ns:hasDownStreamNode ?downnode.
?downnode ns:hasLocation ?loc2. 
BIND ( (xsd:decimal(?loc2) - xsd:decimal(?loc)) as ?diff)

} 
ORDER BY DESC(?tier) Asc(abs(?diff))