PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://purl.org/eis/vocab/scor#>

SELECT ?node (sum(xsd:integer(?maketimemetrics)) as ?hasMetricRS_22)
WHERE{
?process :belongsToNode ?node .
?process  :hasMetricRS_33 
		| :hasMetricRS_49 
		| :hasMetricRS_101 
		| :hasMetricRS_114
		| :hasMetricRS_123
		| :hasMetricRS_128
		| :hasMetricRS_142  ?maketimemetrics .
}
GROUP BY (?node)




