PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://purl.org/eis/vocab/scor#>

SELECT ?node (sum(xsd:integer(?delivertimemetrics)) as ?hasMetricRS_23)
WHERE{
?process :belongsToNode ?node .
?process  :hasMetricRS_16 
		| :hasMetricRS_18 
		| :hasMetricRS_46 
		| :hasMetricRS_51
		| :hasMetricRS_102 
		| :hasMetricRS_110 
		| :hasMetricRS_111 
		| :hasMetricRS_117
		| :hasMetricRS_116
		| :hasMetricRS_120
		| :hasMetricRS_124
		| :hasMetricRS_126 ?delivertimemetrics .
}
GROUP BY (?node)






