PREFIX : <http://purl.org/eis/vocab/scor#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
Prefix ns: <http://www.semanticweb.org/ramzy/ontologies/2021/3/untitled-ontology-6#>

Select (AVG (xsd:decimal(?min)) as ?Efficiency)
where 
{
Select ?tier (MAX(?metric) as ?MAX) {
?node :hasAssetManagemenEfficiencyMetric ?metric. 
?node ns:belongsToTier ?tier.
bind (1 as ?x)
} 
Group by (?tier)
}
Group by (?x)
