PREFIX : <http://purl.org/eis/vocab/scor#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
Prefix ns: <http://www.semanticweb.org/ramzy/ontologies/2021/3/untitled-ontology-6#>


Select ?metric  {
?node :hasResponsivenessMetric ?metric. 
?node ns:belongsToTier ?tier.
} 
ORDER BY ASC(?tier) Desc(?metric)
Limit 1