PREFIX : <http://purl.org/eis/vocab/scor#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
Prefix ns: <http://www.semanticweb.org/ramzy/ontologies/2021/3/untitled-ontology-6#>

Select (SUM (xsd:decimal(?min)) as ?sum)
where 
{
Select ?tier (MIN(?metric) as ?min) {
?node :hasCostMetric ?metric. 
?node ns:belongsToTier ?tier.
bind (1 as ?x)
} 
Group by (?tier)
}
Group by (?x)
